version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: planning-poker-db
    environment:
      POSTGRES_DB: planning_poker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planning-poker-network

  backend:
    build: ./backend
    container_name: planning-poker-backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: planning_poker
      NODE_ENV: development
    depends_on:
      - postgres
    networks:
      - planning-poker-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: planning-poker-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - planning-poker-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  planning-poker-network:
    driver: bridge
